import type { Portfolio } from '@/types'

// ---------------------------------------------------------------------------
// MOCK_PORTFOLIO — Curated demo scenario: Aria Chen
//
// Story: Aria has 100M total CAU capacity. She's currently sitting on ~1.1M
// available SCU (partially depleted from active outbound leases). Her CC
// balance is slightly negative — she owes $1,847 to the network from recent
// SCU purchases. This puts her in the "debt" state visible on first load.
// ---------------------------------------------------------------------------
export const MOCK_PORTFOLIO: Portfolio = {
  userId:   'usr_aria_chen',
  userName: 'Aria Chen',
  cau: {
    id:                    'cau-001',
    totalUnits:            100_000_000,   // 100M CAU
    productionRatePerHour: 4_320,         // SCU/hr generated by hardware
  },
  scu: {
    available:  1_087_340,   // ~1.1M available (irregular — not round)
    consumed:     342_810,   // consumed over session
    reserved:     210_000,   // reserved for pending ops
    leasedOut:  1_340_000,   // currently leased out (sum of outbound leases below)
    total:    100_000_000,   // 100M total SCU capacity
  },
  cc: {
    balance: -1_847,         // NEGATIVE — debt state. Triggers red CC card in Phase 2/4.
  },
}
